### ISSUE TITLE
什么时候开源代码，我想学习下

### ISSUE THREAD

**Issue by wuhongsheng** [yxlu-0102/AP-BWE#3]

**Comment by yxlu-0102** [comment]
I am very sorry, but since our paper is still under review by the journal, we are unable to open source the code at this time.

However, you can refer to this reproduced version by someone else: https://github.com/xinan-chen/AP_BWE.

We will open source the code as soon as the paper is accepted.

**Comment by wuhongsheng** [comment]
> I am very sorry, but since our paper is still under review by the journal, we are unable to open source the code at this time.
> 
> However, you can refer to this reproduced version by someone else: https://github.com/xinan-chen/AP_BWE.
> 
> We will open source the code as soon as the paper is accepted.

感谢分享
