### ISSUE TITLE
The impact of very large batch sizes

### ISSUE THREAD

**Issue by Respaired** [yxlu-0102/AP-BWE#4]
Hi. thanks for bringing us this model.
i was wondering what would be the impact of increasing the batch size to large numbers (256 or 512) since this model seem to be very light and I'm not getting OOM, at least not in the first 100 steps i've tested so far.

I have heard that a larger batch size may cause the discriminator to dominate as it sees a large number of samples in each step, so I'm concerned if it's safe to increase the batch size to however much I can.

my data have roughly 520,000 samples which is around 760 hrs.

btw, may i also ask you to share your logs so we can use it as a reference? 
thanks.

**Comment by yxlu-0102** [comment]
I'm so sorry bro that I deleted all the log files after training, since there were so many sets of experiments and the total log files were so big.

But considering your concerns, I have tried to increase the batch size to 64 and the performance seemed unaffected. So I would be fine to increase the batch size to an appropriate number.

**Comment by Respaired** [comment]
No problem at all! Thanks.

well i tried with a batch size of 312, I can only assume a SNR of 19 can be a good thing.
the reconstructed audio are also solid. the model seem to have converged after 50k steps. 

here's my graphs for anybody who may need it.
![image](https://github.com/user-attachments/assets/c71b7e16-68c8-420a-b318-b6dee4075abf)
![image](https://github.com/user-attachments/assets/8d89fb3f-8baa-4d27-9368-6ac408e068d5)

I wish there was a trivial way to separate input / ground truth like MPSnet. I'm quite curios how possible it is to combine BWE + enhancement at 48khz.
